const String kAppTypeFlutter = "flutter";
const String kAppTypeConsole = "console";

const String kAppRootOption = "app-root";
const String kPythonModuleOption = "python-module";
const String kAppTypeOption = "app-type";
const String kPythonModulesRootOption = "python-modules-root";

const String kPythonModulesGeneratedHeader = """
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by dartpip. It should be version controlled.
""";
const String kPythonModulesPrefix = "const String kPythonModules = \"";
const String kPythonModulesSuffix = "\";";

const String kBase64RegexSource = r"([a-zA-Z0-9+\/]*={0,2})";

final RegExp kPythonModulesDartRegex = RegExp(
  "^${kPythonModulesPrefix.replaceAll(RegExp(r"\s+"), r"\s+")}$kBase64RegexSource$kPythonModulesSuffix",
  multiLine: true,
);
