part of dartpip;

const String _kAppTypeFlutter = "flutter";
const String _kAppTypeConsole = "console";

const String _kAppRootOption = "app-root";
const String _kPythonModuleOption = "python-module";
const String _kAppTypeOption = "app-type";
const String _kPythonModulesRootOption = "python-modules-root";

const String _kPythonModulesGeneratedHeader = """
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by dartpip. It should be version controlled.
""";
const String _kPythonModulesPrefix = "const String kPythonModules = \"";
const String _kPythonModulesSuffix = "\";";

const String _kBase64RegexSource = r"([a-zA-Z0-9+\/]*={0,2})";

final RegExp _kPythonModulesDartRegex = RegExp(
  "^${_kPythonModulesPrefix.replaceAll(RegExp(r"\s+"), r"\s+")}$_kBase64RegexSource$_kPythonModulesSuffix",
  multiLine: true,
);
