name: dart_python_ffi
repository: https://github.com/IVLIVS-III/dart_python_ffi

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze . --fatal-infos
  compile-dartpip:
    exec: dart compile exe bin/dartpip.dart -o ../../bin/dartpip
    select-package:
      scope: dartpip
  compile-example:
    exec: dart compile exe bin/python_ffi_dart_example.dart -o ../../../bin/example
    select-package:
      scope: python_ffi_dart_example
  ffigen:
    exec: |
      dart run ffigen
      melos run post_ffigen
    select-package:
      scope: python_ffi_macos_dart
  post_ffigen:
    exec: perl -0777 -pi -e "s/import 'dart:ffi' as ffi;/import 'dart:ffi' as ffi;\\n\\npart '..\/extensions\/bindings_extension.dart';/igs" lib/src/ffi/generated_bindings.g.dart
    select-package:
      scope: python_ffi_macos_dart
  format:
    exec: dart format .
  doc:
    exec: dart doc .
  postbootstrap: melos run ffigen
