name: dart_python_ffi
repository: https://github.com/IVLIVS-III/dart_python_ffi

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze . --fatal-infos
  ffigen:
    exec: |
      dart run ffigen
      melos run post_ffigen
    select-package:
      scope: python_ffi_macos_dart
  post_ffigen:
    exec: perl -0777 -pi -e "s/import 'dart:ffi' as ffi;/import 'dart:ffi' as ffi;\\npart '..\/extensions\/bindings_extension.dart';/igs" lib/src/ffi/generated_bindings.g.dart
    select-package:
      scope: python_ffi_macos_dart
  format:
    exec: dart format .
  postbootstrap: melos run ffigen
