name: dart_python_ffi
repository: https://github.com/IVLIVS-III/dart_python_ffi

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze . --fatal-infos
  ffigen:
    exec: dart run ffigen
    select-package:
      scope: python_ffi_macos
  format:
    exec: dart format .
  postbootstrap: melos run ffigen
