name: dart_python_ffi
repository: https://github.com/IVLIVS-III/dart_python_ffi

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true
    hooks:
      post: melos run ffigen

scripts:
  analyze:
    exec: dart analyze . --fatal-infos
  compile-dartpip:
    exec: dart compile exe bin/dartpip.dart -o ../../bin/dartpip
    packageFilters:
      scope: dartpip
  ffigen:
    exec: |
      dart run ffigen
      melos run post_ffigen
    packageFilters:
      scope:
        - python_ffi_cpython_dart
  post_ffigen:
    exec: |
      perl -0777 -pi -e "s/import 'dart:ffi' as ffi;/import 'dart:ffi' as ffi;\\n\\npart '..\/extensions\/bindings_extension.dart';/igs" lib/src/ffi/generated_bindings.g.dart
      perl -0777 -pi -e "s/\\nclass/\\nbase class/igs" lib/src/ffi/generated_bindings.g.dart
      perl -0777 -pi -e "s/\\nabstract class/\\nabstract class/igs" lib/src/ffi/generated_bindings.g.dart
    packageFilters:
      scope:
        - python_ffi_cpython_dart
  format:
    exec: dart format . && git restore **/*.g.dart
  doc:
    exec: dart doc .
  outdated:
    exec: dart pub get && dart pub outdated
  test:
    exec: dart test
