name: dartpip_solver
description: Version solver used by the `dartpip` command to resolve python modules.
version: 0.0.5
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  archive: ^3.4.2
  cli_util: ^0.4.0
  collection: ^1.18.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  python_ffi_dart: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  python_ffi_lint_dart: ^0.1.1
  test: ^1.24.6

python_ffi:
  modules:
    packaging: ^23.1
