name: dartpip_solver
description: Version solver used by the `dartpip` command to resolve python modules.
version: 0.0.1
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  archive: ^3.3.7
  cli_util: ^0.4.0
  collection: ^1.18.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  python_ffi_dart: ^0.3.1

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  python_ffi_lint_dart: ^0.1.0
  test: ^1.21.0

python_ffi:
  modules:
    packaging: ^23.1
