name: interface_gen_test
description: A collection of python modules for testing the interface generator.
version: 0.0.1
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: ^3.0.6

dependencies:
  python_ffi_dart: ^0.3.1

dev_dependencies:
  lints: ^2.0.0
  python_ffi_lint_dart: ^0.1.0
  test: ^1.21.0

python_ffi:
  modules:
    empty_module:
      path: python_modules/empty_module.py
    module_field:
      path: python_modules/module_field.py
    module_function:
      path: python_modules/module_function.py
    dataclass:
      path: python_modules/dataclass.py
    inherited_fields_rename:
      path: python_modules/inherited_fields_rename.py
    submodule:
      path: python_modules/submodule
    class_init_adds_field:
      path: python_modules/class_init_adds_field.py
    primitive_types:
      path: python_modules/primitive_types.py
    generic_types:
      path: python_modules/generic_types.py
    class_types:
      path: python_modules/class_types.py
