name: interface_gen_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  python_ffi_dart: ^0.3.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  python_ffi_lint_dart: ^0.1.0
  test: ^1.21.0

python_ffi:
  modules:
    class_init_adds_field:
      path: python_modules/class_init_adds_field.py
