name: lark
description: A collection of python modules for testing the package manager.
version: 0.2.1
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: ^3.0.2

dependencies:
  python_ffi_dart: ^0.4.1

dev_dependencies:
  python_ffi_lint_dart: ^0.1.1
  test: ^1.24.6

python_ffi:
  modules:
    lark: ^1.1.5
