name: lark
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  python_ffi_dart: ^0.3.1

dev_dependencies:
  python_ffi_lint_dart: ^0.1.0
  test: ^1.21.0

python_ffi:
  modules:
    lark: ^1.1.5
