include: package:python_ffi_lint_dart/analysis.yaml

linter:
  rules:
    # Strictly copied from https://github.com/flutter/packages/blob/main/packages/flutter_lints/lib/flutter.yaml
    # as it seems not to be possible to include multiple rule sets.
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
