name: python_ffi_lint
description: Analysis options used across the Python-FFI for Dart project.
version: 0.1.0
homepage: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter_lints: ^2.0.1
  python_ffi_lint_dart: ^0.1.0
dev_dependencies:
  test: ^1.24.3
