name: python_ffi_interface
description: A base interface for python_ffi_dart, a Python-FFI for Dart.
version: 0.1.1
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1

dev_dependencies:
  python_ffi_lint_dart: ^0.1.0
  test: ^1.24.3
