name: python_ffi_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  python_ffi_interface: ^0.0.1
  python_ffi_macos_dart: ^0.0.1

dev_dependencies:
  python_ffi_lint: ^0.0.1
  test: ^1.16.0
