name: python_ffi_dart_example
description: The example command line application showcasing the python_ffi_dart package, a Python-FFI for Dart.
version: 0.1.0
repository: https://github.com/IVLIVS-III/dart_python_ffi
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.1
  collection: ^1.17.2
  python_ffi_dart:
    # When depending on this package from a real application you should use:
    #   python_ffi_dart: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the package so we use a path dependency on
    # the parent directory to use the current package's version.
    path: ../

dev_dependencies:
  python_ffi_lint_dart: ^0.1.0
  test: ^1.24.3

python_ffi:
  modules:
    type_mappings:
      path: python-modules/type_mappings.py
    eq_test:
      path: python-modules/eq_test.py
