name: python_ffi_cpython
description: The macOS, Windows and Linux implementation of python_ffi, a Python-FFI for Dart.
version: 0.3.1
homepage: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  plugin_platform_interface: ^2.1.4
  python_ffi_cpython_dart: ^0.3.1
  python_ffi_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  python_ffi_lint: ^0.1.0
  test: ^1.24.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/python3.11.zip
  plugin:
    implements: python_ffi
    platforms:
      macos:
        ffiPlugin: true
        fileName: python_ffi_cpython.dart
        dartPluginClass: PythonFfiCPython
      windows:
        ffiPlugin: true
        fileName: python_ffi_cpython.dart
        dartPluginClass: PythonFfiCPython
      linux:
        ffiPlugin: true
        fileName: python_ffi_cpython.dart
        dartPluginClass: PythonFfiCPython

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
