name: dartpip
description: |
  Add Python modules (packages) to your Dart or Flutter project.
  Like `pip`, but for Dart, heavily inspired by the `pub` command.
version: 0.0.1
repository: https://github.com/IVLIVS-III/dart_python_ffi/packages/dartpip

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  args: ^2.4.0
  collection: ^1.17.0
  yaml: ^3.1.1

dev_dependencies:
  python_ffi_lint: ^0.0.1
  test: ^1.21.0
