name: python_ffi_macos_dart
description: The macOS implementation of python_ffi_dart, a Python-FFI for Dart.
version: 0.0.1
homepage: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  ffi: ^2.0.1
  python_ffi_interface: ^0.0.1

dev_dependencies:
  ffigen: ^7.2.9
  python_ffi_lint_dart: ^0.0.1
  test: ^1.24.0

platforms:
  macos:

ffigen:
  name: "DartPythonCBindings"
  output: 'lib/src/ffi/generated_bindings.g.dart'
  description: "Bindings to Python C interface"
  headers:
    entry-points:
      - 'python/Headers/Python.h'
    include-directives:
      - 'python/Headers/*'
  globals:
    rename:
      "_(.*)": "$1"
      "__(.*)": "$1"
