name: python_ffi_macos_dart
description: The macOS implementation of python_ffi_dart, a Python-FFI for Dart.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  gunnison:
    git:
      url: https://github.com/IVLIVS-III/gunnison.git
      path: gunnison
  gunnison_assets:
    git:
      url: https://github.com/IVLIVS-III/gunnison.git
      path: gunnison_assets
  ffi: ^2.0.1
  python_ffi_interface: ^0.0.1

dev_dependencies:
  gunnison_builder:
    git:
      url: https://github.com/IVLIVS-III/gunnison.git
      path: gunnison_builder
  ffigen: ^7.2.0
  python_ffi_lint: ^0.0.1
  test: ^1.16.0

dependency_overrides:
  gunnison:
    git:
      url: https://github.com/IVLIVS-III/gunnison.git
      path: gunnison
  gunnison_assets:
    git:
      url: https://github.com/IVLIVS-III/gunnison.git
      path: gunnison_assets

ffigen:
  name: "DartPythonCBindings"
  output: 'lib/src/ffi/generated_bindings.g.dart'
  description: "Bindings to Python C interface"
  preamble: |
    // ignore_for_file: unused_field, unused_element
  headers:
    entry-points:
      - 'python/Headers/Python.h'
    include-directives:
      - 'python/Headers/*'
  #  functions:
  #    rename:
  #      "_(.*)": "$1"
  #      "__(.*)": "$1"
  #  structs:
  #    rename:
  #      "_(.*)": "$1"
  #      "__(.*)": "_$1"
  #    member-rename:
  #      "_(.*)":
  #        "_(.*)": "$1"
  #  unnions:
  #    rename:
  #      "_(.*)": "$1"
  #      "__(.*)": "$1"
  #    member-rename:
  #      "_(.*)":
  #        "_(.*)": "$1"
  globals:
    rename:
      "_(.*)": "$1"
      "__(.*)": "$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
#  enums:
#    rename:
#      "_(.*)": "$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
#  typedefs:
#    rename:
#      "_(.*)": "$1"
#      "__(.*)": "$1"
