name: python_ffi_macos_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  ffi: ^2.0.1
  python_ffi_interface: ^0.0.1

dev_dependencies:
  ffigen: ^7.2.0
  python_ffi_lint: ^0.0.1
  test: ^1.16.0

ffigen:
  name: "DartPythonCBindings"
  output: 'lib/src/ffi/generated_bindings.g.dart'
  description: "Bindings to Python C interface"
  preamble: |
    // ignore_for_file: unused_field, unused_element
  headers:
    entry-points:
      - 'python/Headers/Python.h'
    include-directives:
      - 'python/Headers/*'
#  functions:
#    rename:
#      "_(.*)": "$1"
#      "__(.*)": "$1"
#  structs:
#    rename:
#      "_(.*)": "$1"
#      "__(.*)": "_$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
#  unnions:
#    rename:
#      "_(.*)": "$1"
#      "__(.*)": "$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
  globals:
    rename:
      "_(.*)": "$1"
      "__(.*)": "$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
#  enums:
#    rename:
#      "_(.*)": "$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
#  typedefs:
#    rename:
#      "_(.*)": "$1"
#      "__(.*)": "$1"
