name: basic_dataclass
description: A sample command-line application to showcase importing a Python module that defines its own Python class.
version: 0.0.1
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  python_ffi_dart: ^0.2.1

dev_dependencies:
  python_ffi_lint_dart: ^0.0.1
  test: ^1.24.2

python_ffi:
  modules:
    basic_dataclass: any
