name: transitive_dependencies_test
description: A collection of python modules for testing the package manager.
version: 0.0.1
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: ^3.0.6

dependencies:
  python_ffi_dart: ^0.3.1

dev_dependencies:
  lints: ^2.0.0
  python_ffi_lint_dart: ^0.1.0
  test: ^1.21.0

python_ffi:
  modules:
