name: basic_cli_adder
description: A sample command-line application to showcase importing a simple Python module.
version: 0.0.1
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  python_ffi_dart: ^0.0.2

dev_dependencies:
  python_ffi_lint_dart: ^0.0.1
  test: ^1.24.0

python_ffi:
  modules:
    basic_cli_adder: any
