name: basic_cli_adder
description: A sample command-line application to showcase importing a simple Python module.
version: 0.1.0
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  python_ffi_dart: ^0.3.1

dev_dependencies:
  python_ffi_lint_dart: ^0.1.0
  test: ^1.24.3

python_ffi:
  modules:
    basic_cli_adder:
      path: python-modules/basic_cli_adder.py
