name: flutter_package_import
description: A Flutter app which imports a package, wrapping a python module.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_package_export: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  python_ffi: ^0.3.1
  python_ffi_cpython: ^0.3.1
  python_ffi_lint: ^0.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
