name: python_ffi_cpython_dart
description: The macOS, Windows and Linux implementation of python_ffi_dart, a Python-FFI for Dart.
version: 0.4.2
homepage: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.2
  cli_util: ^0.4.0
  crypto: ^3.0.3
  ffi: ^2.1.0
  path: ^1.8.3
  python_ffi_interface: ^0.2.0

dev_dependencies:
  ffigen: ^9.0.1
  python_ffi_lint_dart: ^0.1.1
  test: ^1.24.6

platforms:
  macos:
  windows:
  linux:

ffigen:
  name: "DartPythonCBindings"
  output: 'lib/src/ffi/generated_bindings.g.dart'
  description: "Bindings to Python C interface"
  headers:
    entry-points:
      - 'python/Headers/Python.h'
    include-directives:
      - 'python/Headers/**'
  globals:
    rename:
      "_(.*)": "$1"
      "__(.*)": "$1"
