name: python_ffi_dart_example
description: The example command line application showcasing the python_ffi_dart package, a Python-FFI for Dart.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  args: ^2.4.0
  collection: ^1.17.0
  python_ffi_dart: ^0.0.1

dev_dependencies:
  python_ffi_lint_dart: ^0.0.1
  test: ^1.24.0

python_ffi:
  modules:
    type_mappings: any
