name: pytimeparse_dart
description: A simple Dart package wrapping pytimeparse.
version: 0.2.2
repository: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  python_ffi_dart: ^0.4.4

dev_dependencies:
  python_ffi_lint_dart: ^0.1.1
  test: ^1.24.6

python_ffi:
  modules:
    pytimeparse: any
