name: python_ffi_macos
description: A Python-FFI for Dart
version: 0.0.1
homepage: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  plugin_platform_interface: ^2.1.3
  python_ffi_platform_interface: ^0.0.1

dev_dependencies:
  ffigen: ^7.2.0
  flutter_test:
    sdk: flutter
  python_ffi_lint: ^0.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: python_ffi
    platforms:
      macos:
        ffiPlugin: true
        fileName: python_ffi_macos.dart
        dartPluginClass: PythonFfiMacOS

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/libpython3.11.dylib
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

ffigen:
  name: "DartPythonCBindings"
  output: 'lib/src/ffi/generated_bindings.g.dart'
  description: "Bindings to Python C interface"
  preamble: |
    // ignore_for_file: unused_field, unused_element
  headers:
    entry-points:
      - 'python/Headers/Python.h'
    include-directives:
      - 'python/Headers/*'
#  functions:
#    rename:
#      "_(.*)": "$1"
#      "__(.*)": "$1"
#  structs:
#    rename:
#      "_(.*)": "$1"
#      "__(.*)": "_$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
#  unnions:
#    rename:
#      "_(.*)": "$1"
#      "__(.*)": "$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
  globals:
    rename:
      "_(.*)": "$1"
      "__(.*)": "$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
#  enums:
#    rename:
#      "_(.*)": "$1"
#    member-rename:
#      "_(.*)":
#        "_(.*)": "$1"
#  typedefs:
#    rename:
#      "_(.*)": "$1"
#      "__(.*)": "$1"
