name: python_ffi_lint_dart
description: Analysis options used across the Python-FFI for Dart project.
version: 0.1.1
homepage: https://github.com/IVLIVS-III/dart_python_ffi

environment:
  sdk: '>=3.0.0 <4.0.0'

topics:
  - analysis
  - lints

dependencies:
  lints: ^2.1.1

dev_dependencies:
  test: ^1.24.6
